### PR TITLE
Implements all functions from libsecp256k1-zkp

### PR DESCRIPTION
**Pull request by NicolasFlamel1**
This PR implements all 93 functions from [secp256k1-zkp](https://github.com/mimblewimble/secp256k1-zkp). This fulfills all the requirements of the [Python CFFI secp256k1-zkp wrapper bounty](https://forum.grin.mw/t/locked-python-cffi-secp256k1-zkp-wrapper-bounty/10030) established by the Grin CC. Those requirements are as follows:

1. Well documented Wrapper
    - The documentation for all the functions that this wrapper provides can be found in documentation.md.
2. Well tested (test cases should be made available)
    - Test cases for all the functions that this wrapper provides can be found in test_secp256k1_mw.py and can be tested with pytest.
3. Open source, Apache License 2.0, if not possible with wrapped C code, MIT license
    - The code in defs.c must be under MIT license since it's taken directly from secp256k1-zkp.
    -  Everything else can be under any license that this project deems fit.

### CODE REVIEW

**Comment by NicolasFlamel1** [comment]
@marekyggdrasil any updates on reviewing this PR?

**Comment by marekyggdrasil** [comment]
@NicolasFlamel1 thank you for taking the initiative to pick-up this project. I have finished the review and everything works as expected. The details regarding the prize are [in the forum post](https://forum.grin.mw/t/locked-python-cffi-secp256k1-zkp-wrapper-bounty/10030/5?u=renzokuken).

If it is not too much trouble, could you pull from the master branch and resolve the conflicts? Please take into account there were some minor changes to `build.py` that allow the wrapper to be build from any directory (how paths are managed) and the `setup.py` was created to distribute the wrapper as Python module. Please also let me know if you wish to be listed as a maintainer (no pressure, entire up to you).

**Comment by NicolasFlamel1** [comment]
@marekyggdrasil I've finished resolving the conflicts and changing the code to function properly as a Python module. I've also added my name as the maintainer in the `setup.py` file.

**Comment by marekyggdrasil** [comment]
Thank you for great work!

**Comment by marekyggdrasil** [comment]
Forgot to mention, I also don't mind if you list yourself as the author. I will merge this PR and if you wish to be the author of this module please open a new PR with that change and I will merge immediately!

**Comment by NicolasFlamel1** [comment]
Let's keep you listed as the author. I don't want my contributions to detract from your initiative in creating this project.

**Pull request merged**
